### ISSUE TITLE
Move the _setInitialStates and _validateAndSetProps methods out of the class 

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/component#13]
This could lead to a reduced memory usage, since lesser methods are forwarded into extended classes.
The methods itself also benefit from this approach since they can't get executed multiple times in a single instance by the developer.

**Comment by grebaldi** [comment]
will take care of this one

**Comment by Inkdpixels** [comment]
You guys are nuts! Thank you @grebaldi @akoenig! :tada:

**Comment by Inkdpixels** [comment]
Done and will be inside the upcoming v1.1.0.
