### ISSUE TITLE
Proposal: Injectable validators

### ISSUE THREAD

**Issue by akoenig** [reduct/component#15]
The following is a proposal for injecting custom `propType` validators:

``` html
<div data-component="TwitterStream"
        data-url="https://api.twitter.com/1.1/statuses/user_timeline.json"></div>
```

``` js
import url from 'proptypes-url-validator';

const TwitterStreamPropTypes = {
    'url': nodeProto.propTypes.is(url).isRequired
};
```

The respective validator has to expose a function which performs the actual validation.

**Comment by Inkdpixels** [comment]
Sounds pretty great and extensible, this opens the door for many validators, and even Component related validators. I really dig the way you think @akoenig ! :+1:

**Comment by Inkdpixels** [comment]
Just another thought, maybe we can add some custom validators to the repository, or even create it's own repository.
In the first case, we could import them separately e.g.

``` js
import propTypes from 'nodeProto/propTypes'
```

The second case also has it's benefits, since they are 100% standalone and not bound to this repository. What do you think?

**Comment by akoenig** [comment]
I guess it would also be cool to separate the propType logic into an own module. Something like `nodeproto-proptypes` which could be exposed through `nodeproto` but used as a standalone module as well.

Standalone mode:

``` js
import proptypes from 'nodetype-proptypes';
import email from './email-validator';

const schema = {
    'email': proptypes.is(email).isRequired
};

proptypes(schema).isValid(theActualPropTypeObject); // => boolean

```

**Comment by akoenig** [comment]
haha ... We had the same idea at the same time. Nice! :)

**Comment by Inkdpixels** [comment]
Closed since this issue will be handled over at the nitpick library.
