### ISSUE TITLE
Add a selector argument for getElement()

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/component#22]
We should integrate an selector argument for the getElement() method, which uses the querySelectorAll API. The getElement() method should return an array, not a DOMList if an argument was given.

**Comment by akoenig** [comment]
+1 – Will integrate this.

**Comment by akoenig** [comment]
@Inkdpixels Done :)

**Comment by Inkdpixels** [comment]
Couldn't be more happier with the result, let me tell you that! Thank you @akoenig :dancers:

**Comment by Inkdpixels** [comment]
Re-Opened since it isn't merged yet.

I also thought about the syntax/methodName for this feature.

Maybe we should move this logic into a separate method, named `this.getElements('mySelector')` - Since the functions returns an array the trailing `s` makes more sense to me. But still, we should leave the `getElement` method, and maybe integrate a selector option in there as well, which then uses `querySelector()` instead of `querySelectorAll()` which the `getElements()` method uses.

Thoughts about that @akoenig @grebaldi?

**Comment by akoenig** [comment]
Yeah, thought about the very same thing. The semantic of this method is wrong, but thought about implementing it anyway to have a discussion basis :)

**Comment by Inkdpixels** [comment]
Soooo... Do you want to integrate this as well? 
Or do you see any problems with the suggestion of mine?

**Comment by akoenig** [comment]
Jap, will implement it.

**Comment by Inkdpixels** [comment]
Awesome - Thanks!
Bear in mind that I will transfer the repository to the organization this evening. So you may want to wait for this to avoid conflicts while pushing/pulling. :)

**Comment by akoenig** [comment]
Haha ... It's already there.

**Comment by grebaldi** [comment]
For semantics: `find` and `findOne` -> or both of them suffixed with `Element`

`get` would suggest, that one could rely on it having a result, `find` is imho generally more appropriate for query things.

**Comment by Inkdpixels** [comment]
+1 for this @grebaldi

**Comment by akoenig** [comment]
Resolved in #56.
