### ISSUE TITLE
Move from Jest to the standarized test suite

### ISSUE THREAD

**Issue by Inkdpixels** [reduct/component#28]
It seems like jest can't handle @ signs in the package name(what?). We also had some major problems with jest in the past, and as of consistency we should prioritize the move from jest to our yet to defined standard.

https://github.com/reduct/discussions/issues/6

**Comment by akoenig** [comment]
Have built the workflow with `mocha`, `chai` and `jsdom` in the `refactoring/api` branch of `assembler`, see: [Assembler.spec.js](https://github.com/reduct/assembler/blob/refactoring/api/Tests/Assembler.spec.js).

**Comment by Inkdpixels** [comment]
This task is done and the corresponding issue can be closed after the next minor release of @reduct/build-tools consisting of https://github.com/reduct/build-tools/pull/12

**Comment by Inkdpixels** [comment]
Closed in favor of 7600c36
