### ISSUE TITLE
More/better code documentation

### ISSUE THREAD

**Issue by grebaldi** [reduct/component#31]
Just a brief statement: Let's document everything.

jsdoc? I added some in https://github.com/reduct/component/pull/30

**Comment by Inkdpixels** [comment]
I used JSDoc in the past, but my position regarding this moved towards 'readable code over big documentation blocks' in the past. 

At this moment I see one benefit for documenting with JSDoc: The IDE integration(type/argument suggestions etc.). Are there any other benefits which speaking code doesn't cover?

**Comment by Inkdpixels** [comment]
I thinks this issue should also be moved into the discussions repository since it's more of an general decision for all repositories.
