### ISSUE TITLE
Allow for plain objects as single argument in setState

### ISSUE THREAD

**Issue by grebaldi** [reduct/component#32]
This needs a little discussion, because imho we have a tiny but crucial semantical problem here. 

Currently regarding the state, every key/value pair is considered to be **a** state. But I think it would be more consistent to consider the whole key/value store as **the** state of the component, since it can only be in **one** state, that is completely defined by this states keys and values.

So either we keep `setState` and rename a couple of methods that refer to `states`, or the method proposed by this issue gets implemented as `setStates`.

@akoenig @Inkdpixels

**Comment by Inkdpixels** [comment]
As discussed yesterday and noted [here](https://github.com/reduct/discussions/wiki/%5B28.07.2015%5D-Protocol#component) - We agreed that the setState method should only accept one object as the arguments and this 'incoming' object should be merged with the previous state object.

**Comment by Inkdpixels** [comment]
Merged in development and pinned for the 2.0.0 release.
