### ISSUE TITLE
`getDefaultProps` not working when no propTypes defined

### ISSUE THREAD

**Issue by akoenig** [reduct/component#50]
Consider the following component:

``` js

import { Component } from '@reduct/component';

class Foo extends Component {

    constructor (el, props) {
         super(el, {props});

         console.log(this.getProp('bar'));
    }

    getDefaultProps () {
        return {
            bar: 'zoo'
        };
    }
```

So `bar` is always `undefined`. This is a desired behavior because `bar` would be an internal property (`this.bar`). Nonetheless, `component` should print a warning, when `getDefaultProps` has been defined, but no `propTypes` were provided.

**Comment by Inkdpixels** [comment]
If you don't mind I will label this as an enhancement. :)
