### ISSUE TITLE
Component decorator

### ISSUE THREAD

**Issue by akoenig** [reduct/component#60]
Move the `@Component()` decorator from the [lightfold](https://github.com/akoenig/lightfold) project over.

**Comment by akoenig** [comment]
We have to find a possibility for exposing the `@Component` decorator from the bundled version. From my point of view, the optimal solution would be the following example (this should be the `index.js` within the `@reduct` package):

``` js
// `index.js` in our new @reduct package

import Component from '@reduct/component';

export {
    Component
};
```

and then:

``` js
import {Component} from 'reduct';

@Component()
class MyComponent {...}
```

If someone wants to use `@reduct/component` directly we should expose the class as:

``` js
import ComponentClass from '@reduct/component';

class MyComponent extends ComponentClass {}
```

@Inkdpixels @grebaldi Any thoughts on this how we want to achieve this with the current bundling process?

**Comment by Inkdpixels** [comment]
Hey @akoenig! Sounds good and exactly like what we've discussed a few weeks ago in our last @reduct meetup, or am I missing something new? Anyhow, thank you that you've taken this issue upon you :)

**Comment by akoenig** [comment]
Hey @Inkdpixels, not sure if we discussed this problem in brief detail. What I meant was, that we have a naming collision here. `Component` for the decorator and `what` (?) for the actual `Component` class.

**Comment by Inkdpixels** [comment]
Yep sure - But I think we agreed on something similar, so I am totally fine with the suggestion in this issue :D
